apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
    spec:
      volumeMounts:
      - name: config-volume
        configMap:
          name: my-configmap
      containers:
      - name: mon-app
        image: rletient/hello:0.0.3
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        env:
        - name: JAVA_OPS
          value: "-Dspring.config.location=file:/etc/config/application.yaml"
        - name: MYENV_SECRET
          valueFrom:
            secretKeyRef:
              name: hello-secrets
              key: myenv.secret


