apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: my-configmap
      containers:
      - name: mon-app
        image: rletient/hello:0.0.6
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        env:
        - name: JAVA_OPTS
          value: "-Dspring.config.location=/etc/config/application.yaml"
        - name: MYENV_SECRET
          valueFrom:
            secretKeyRef:
              name: hello-secrets
              key: myenv.secret
